name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: npm run webpack
    - run: npm run babel
    - name: New release
      uses: ncipollo/release-action@v1.8.10
      with:
        artifacts: 'dist/person-entity-card-bundle.js'
        commit: 'main'
        allowUpdates: 'true'
        owner: 'gerardag'
        repo: 'person-entity-card'
        token: ${{ secrets.GITHUB_TOKEN }}

