name: Tagging

on:
  push:
    branches:
      - main

jobs:
  Tagging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        append_to_pre_release_tag: ''
        default_bump: false
        create_annotated_tag: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
