name: Tagging

on:
  push:
    branches:
      - main

jobs:
  Tagging:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch
    - uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}