name: Tagging and Releasing

on:
  push:
    branches:
      - main

jobs:
  Tagging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        append_to_pre_release_tag: ''
        default_bump: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - if: ${{ steps.tag_version.outputs.previous_tag == steps.tag_version.outputs.new_tag }}
      run: exit_with_success

    - if: failure()
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - if: failure()
      run: npm install
    - if: failure()
      run: npm run lint
    - if: failure()
      run: npm run webpack
    - if: failure()
      run: npm run babel
    - if: failure()
      name: New release
      uses: ncipollo/release-action@v1.8.10
      with:
        allowUpdates: true
        artifacts: 'dist/person-entity-card-bundle.js'
        body: ${{ steps.tag_version.outputs.changelog }}
        commit: 'main'
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        owner: 'gerardag'
        repo: 'person-entity-card'
        tag: ${{ steps.tag_version.outputs.new_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}


